services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3200:3200"
    # env_file: # Uncomment for local testing
    #   - ./backend/.env 
    environment: # Comment this for local testing
      DB_HOST: ${DB_HOST} # Pull these env variables from AWS SSM
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    # env_file: # Uncomment for local testing
    #   - ./frontend/.env 
    environment: # Comment this for local testing
      VITE_API_URL: ${VITE_API_URL} # Pull these env variables from AWS SSM
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge